default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: webapp
  password: Password1
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kamal_playground_development

test:
  <<: *default
  database: kamal_playground_test

production:
  <<: *default
  host: <%= ENV["POSTGRES_HOST"] %>
  port: <%= ENV["POSTGRES_PORT"] %>
  database: <%= ENV["POSTGRES_DATABASE_NAME"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
