default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kamal_playground_development

test:
  <<: *default
  database: kamal_playground_test

production:
  <<: *default
  database: <%= ENV["POSTGRES_DATABASE_NAME"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
